dist: xenial
sudo: false
language: python
python:
- '3.7'
install: pip install codecov tox-travis
script: tox
after_success:
  - codecov
deploy:
  provider: pypi
  user: wayfair  
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    repo: wayfair/pytest-eucalyptus
    branch: master
    tags: true